//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.03.28 at 10:10:01 PM MSK
//


package by.training.webparsing.devices;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DeviceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="DeviceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name"
 *         type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="origin"
 *         type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="price"
 *         type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="type"
 *         type="{http://www.webparsing.training.by/devices}Type"/>
 *         &lt;element name="date-of-delivery"
 *         type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceType", propOrder = {
    "name",
    "origin",
    "price",
    "type",
    "dateOfDelivery"
})
@XmlSeeAlso({
    PeripheralDevice.class,
    InnerDevice.class
})
public abstract class DeviceType {

    /**
     * name of device.
     */
    @XmlElement(required = true, defaultValue = "absent")
    private String name;
    /**
     * country were was created device.
     */
    @XmlElement(required = true, defaultValue = "absent")
    private String origin;
    /**
     * price of device.
     */
    @XmlElement(required = true, defaultValue = "1")
    @XmlSchemaType(name = "positiveInteger")
    private BigInteger price;
    /**
     * type of device.
     */
    @XmlElement(required = true)
    private Type type;
    /**
     * data when device was delivered.
     */
    @XmlElement(name = "date-of-delivery", required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar dateOfDelivery;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String )
     */
    public void setName(final String value) {
        this.name = value;
    }

    /**
     * Gets the value of the origin property.
     *
     * @return
     *     possible object is
     *     {@link String }
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     */
    public void setOrigin(final String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the price property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     */
    public BigInteger getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     */
    public void setPrice(final BigInteger value) {
        this.price = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link Type }
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link Type }
     */
    public void setType(final Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the dateOfDelivery property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDateOfDelivery() {
        return dateOfDelivery;
    }

    /**
     * Sets the value of the dateOfDelivery property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     */
    public void setDateOfDelivery(final XMLGregorianCalendar value) {
        this.dateOfDelivery = value;
    }

}
