//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.03.28 at 10:10:01 PM MSK
//


package by.training.webparsing.devices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PeripheralDevice complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="PeripheralDevice">
 *   &lt;complexContent>
 *     &lt;extension
 *     base="{http://www.webparsing.training.by/devices}DeviceType">
 *       &lt;sequence>
 *         &lt;element name="connection">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Bluetooth"/>
 *               &lt;enumeration value="Wire"/>
 *               &lt;enumeration value="Wi-Fi"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeripheralDevice", propOrder = {
    "connection"
})
public class PeripheralDevice
    extends DeviceType {
    /**
     * type of connection of Peripheral Device.
     */
    @XmlElement(required = true)
    private String connection;
    /**
     * Gets the value of the connection property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * @param value
     * allowed object is
     * {@link String }
     */
    public void setConnection(final String value) {
        this.connection = value;
    }

}
