//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.03.28 at 10:10:01 PM MSK
//


package by.training.webparsing.devices;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="power-usage"
 *         type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="group-of-complects"
 *         type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute name="cooler" use="required"
 *       type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="critical"
 *       type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ports" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="USB"/>
 *             &lt;enumeration value="LPT"/>
 *             &lt;enumeration value="COM"/>
 *             &lt;enumeration value="none"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type", propOrder = {

})
public class Type {

    /**
     * power usage of device.
     */
    @XmlElement(name = "power-usage", required = true, defaultValue = "1")
    @XmlSchemaType(name = "positiveInteger")
    private BigInteger powerUsage;
    /**
     * group of complects of my device.
     */
    @XmlElement(name = "group-of-complects", required = true, defaultValue =
            "absent")
    private String groupOfComplects;
    /**
     * variable shows do exist cooler in device or don't.
     */
    @XmlAttribute(name = "cooler", required = true)
    private boolean cooler;
    /**
     * variable show is our device critical for computer.
     */
    @XmlAttribute(name = "critical")
    private Boolean critical;
    /**
     * which kind of port our device has.
     */
    @XmlAttribute(name = "ports", required = true)
    private String ports;

    /**
     * Gets the value of the powerUsage property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     */
    public BigInteger getPowerUsage() {
        return powerUsage;
    }

    /**
     * Sets the value of the powerUsage property.
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     */
    public void setPowerUsage(final BigInteger value) {
        this.powerUsage = value;
    }

    /**
     * Gets the value of the groupOfComplects property.
     *
     * @return
     *     possible object is
     *     {@link String }
     */
    public String getGroupOfComplects() {
        return groupOfComplects;
    }

    /**
     * Sets the value of the groupOfComplects property.
     * @param value
     *     allowed object is
     *     {@link String }
     */
    public void setGroupOfComplects(final String value) {
        this.groupOfComplects = value;
    }

    /**
     * Gets the value of the cooler property.
     * @return - cooler
     */
    public boolean isCooler() {
        return cooler;
    }

    /**
     * Sets the value of the cooler property.
     * @param value - do cooler exist in devise or don't
     */
    public void setCooler(final boolean value) {
        this.cooler = value;
    }

    /**
     * Gets the value of the critical property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     */
    public Boolean isCritical() {
        return critical;
    }

    /**
     * Sets the value of the critical property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     */
    public void setCritical(final Boolean value) {
        this.critical = value;
    }

    /**
     * Gets the value of the ports property.
     *
     * @return
     *     possible object is
     *     {@link String }
     */
    public String getPorts() {
        return ports;
    }

    /**
     * Sets the value of the ports property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     */
    public void setPorts(final String value) {
        this.ports = value;
    }

}
